version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=sqlite:///portfolio_api.db
      - JWT_SECRET_KEY=dev-jwt-secret-key-change-in-production
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8080