name = "flask-portfolio-api"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-01-01"

[site]
bucket = "./static"
entry-point = "workers-site"

[env.production]
workers_dev = false
route = "api.yourdomain.com/*"
zone_id = ""

[vars]
FLASK_ENV = "production"